[package]
name = "strata"
version = "0.1.0"
edition = "2021"
build = "build.rs"

[dependencies]
blake3.workspace = true
chrono.workspace = true
clap.workspace = true
records = { path = "../records" }
store = { path = "../store" }
serde_json.workspace = true
serde_yaml.workspace = true
serde.workspace = true
thiserror.workspace = true

[build-dependencies]
kernel = { path = "../kernel" }
